// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxkgPF5PiDqJhH58x1iNkNn4g7Nv2-8dE',
    appId: '1:734157305349:web:d55faa4fda07f50c6e0e6c',
    messagingSenderId: '734157305349',
    projectId: 'ferraria-app',
    authDomain: 'ferraria-app.firebaseapp.com',
    storageBucket: 'ferraria-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1RopMOyGNA1duDfOWImK8A4dftgk0kgg',
    appId: '1:734157305349:android:4db024d800e21a4e6e0e6c',
    messagingSenderId: '734157305349',
    projectId: 'ferraria-app',
    storageBucket: 'ferraria-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxkgPF5PiDqJhH58x1iNkNn4g7Nv2-8dE',
    appId: '1:734157305349:web:23d3c08014bbf9036e0e6c',
    messagingSenderId: '734157305349',
    projectId: 'ferraria-app',
    authDomain: 'ferraria-app.firebaseapp.com',
    storageBucket: 'ferraria-app.firebasestorage.app',
  );
}
